
# configure default values for pull request tests
test-gardener:
  hostprovider: gardener
  baseClusterCloudprovider: gcp

  gardensetup:
    revision:
      prHead: true

  gardener:
    version:
      path: dependency-versions.yaml
      structuredJSONPATH: "versions.gardener.core.version"

  gardener-extensions:
    path: dependency-versions.yaml
    structuredJSONPATH: "versions.gardener.extensions"

  shootFlavors:
  - provider: gcp
    kubernetes:
      versions:
      - version: 1.14.4
  - provider: aws
    kubernetes:
      versions:
      - version: 1.14.4
