
# configure default values for pull request tests
test:
  hostprovider: gardener
  baseClusterCloudprovider: gcp

  gardensetup:
    revision:
      prHead: true

  gardener:
    version:
      path: GARDENER_VERSION

  shootFlavors:
  - cloudprovider: gcp
    kubernetesVersions:
    - version: 1.14.4
  - cloudprovider: aws
    kubernetesVersions:
    - version: 1.14.4
