
# configure default values for pull request tests
test:
  hostprovider: gardener
  baseClusterCloudprovider: gcp

  gardensetup:
    revision:
      prHead: true

  gardener:
    version:
      path: dependency-versions.yaml

  shootFlavors:
  - provider: gcp
    kubernetes:
      versions:
      - version: 1.14.4
  - provider: aws
    kubernetes:
      versions:
      - version: 1.14.4
